diff --git a/src/Makefile b/src/Makefile
index 4b169a7..daca595 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -17,6 +17,11 @@
 #
 ##############################################################################
 
+include $(CONAN_MAKE_FILE)
+CXXFLAGS += $(CONAN_CXXFLAGS) -Wno-unused-variable
+CPPFLAGS += $(CONAN_DEFINES)
+SYSTEMC := $(CONAN_ROOT_SYSTEMC)
+
 ifeq ($(origin CXX),default)
   CXX := g++
 endif
@@ -80,9 +85,12 @@ OBJS := $(SRCS:.cpp=.o)
 DEPS := $(OBJS:.o=.d)
 
 LIB    := libcciapi.a
+SOLIB  := libcciapi.so
 LIBDIR := $(CCI_HOME)/lib
 
-all: $(LIBDIR)/$(LIB)
+all: $(LIBDIR)/$(LIB) $(LIBDIR)/$(SOLIB)
+	@echo CXXFLAGS: $(CXXFLAGS)
+	@echo CPPFLAGS: $(CPPFLAGS)
 
 $(LIBDIR):
 	$(AT_MKDIR)mkdir -p $(LIBDIR)
@@ -91,10 +99,13 @@ $(LIBDIR)/$(LIB): $(OBJS) | $(LIBDIR)
 	$(AT_LIB)$(AR) rcs $@ $^
 	$(AT)ranlib $@
 
+$(LIBDIR)/$(SOLIB): $(OBJS) | $(LIBDIR)
+	$(AT_LIB)$(CXX) $(LDFLAGS) -shared -o $@ $^
+
 -include $(DEPS)
 
 .cpp.o:
-	$(AT_CXX)$(CXX) $(OPT) $(WARN) $(DEFINES) $(INCLUDES) $(CXXFLAGS) -c $< -MMD -o $@
+	$(AT_CXX)$(CXX) $(OPT) $(WARN) $(DEFINES) $(INCLUDES) $(CPPFLAGS) $(CXXFLAGS) -c $< -MMD -o $@
 
 clean:
 	$(AT)rm -vf $(OBJS) $(DEPS)
