find_package(Boost REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(Microsoft.GSL REQUIRED)
find_package(nlohmann_json REQUIRED)
find_package(libxml2 REQUIRED)
find_package(jwt-cpp REQUIRED)
find_package(ZLIB REQUIRED)
if(opentdf_VERSION VERSION_GREATER_EQUAL "1.4.0")
  find_package(magic_enum REQUIRED)
endif()
link_libraries(Boost::boost OpenSSL::SSL Microsoft.GSL::GSL nlohmann_json::nlohmann_json LibXml2::LibXml2 jwt-cpp::jwt-cpp $<TARGET_NAME_IF_EXISTS:magic_enum::magic_enum> ZLIB::ZLIB)
