/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calc_CONSTANTS_H
#define calc_CONSTANTS_H

#include "calc_types.h"

namespace tutorial {

class calcConstants {
 public:
  calcConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const calcConstants g_calc_constants;

} // namespace

#endif
