inputs:
  artifactory-token:
    description: 'Password to authenticate with Artifactory'
    required: false
  artifactory-user:
    description: 'User to authenticate with Artifactory'
    required: false
name: 'Setup Conan'
runs:
  using: "composite"
  steps:
    - run: conan remote add community http://vps-313ae7f5.vps.ovh.net/artifactory/api/conan/conan-local -vtrace
      shell: bash

    - run: |
        conan remote auth community --format=json -vtrace --force | jq ".community | has(\"error\")" | grep -q "false"
      env:
        CONAN_LOGIN_USERNAME_COMMUNITY: ${{ inputs.artifactory-user }}
        CONAN_PASSWORD_COMMUNITY: ${{ inputs.artifactory-token }}
      shell: bash
      if: ${{ inputs.artifactory-user && inputs.artifactory-token }}

    - run: |
        GLOBAL_CONF="$(conan config home)/global.conf"
        echo "core.graph:compatibility_mode=optimized" >> "$GLOBAL_CONF"
      shell: bash
