name: 'Setup Conan'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - run: pip3 install -r requirements.txt
      shell: bash

    - run: conan profile detect --name autodetected --force
      shell: bash
    
    - run: |
        DEFAULT_PROFILE="$(conan config home)/profiles/default"
        echo "include(autodetected)" > "$DEFAULT_PROFILE"
        echo "[replace_requires]" >> "$DEFAULT_PROFILE"
        echo "boost/1.83.0: boost/1.84.0" >> "$DEFAULT_PROFILE"
        echo "geos/3.12.0: geos/3.13.0" >> "$DEFAULT_PROFILE"

        echo "[options]" >> "$DEFAULT_PROFILE"
        echo "boost/*:pch=False" >> "$DEFAULT_PROFILE"
        echo "boost/*:extra_b2_flags=-d2" >> "$DEFAULT_PROFILE"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          if [[ "$RUNNER_ARCH" == "ARM64" ]]; then
            echo "xnnpack/*:assembly=False" >> "$DEFAULT_PROFILE"
          fi
        fi

        echo "[settings]" >> "$DEFAULT_PROFILE"
        if [[ "$RUNNER_OS" == "Windows" && "$RUNNER_ARCH" == "ARM64" ]]; then
          echo "msys2/*:arch=x86_64" >> "$DEFAULT_PROFILE"
          echo "strawberryperl/*:arch=x86_64" >> "$DEFAULT_PROFILE"
        fi

        echo "[conf]" >> "$DEFAULT_PROFILE"
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          echo "tools.system.package_manager:mode=install" >> "$DEFAULT_PROFILE"
          echo "tools.system.package_manager:sudo=True" >> "$DEFAULT_PROFILE"
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "user.openssl:windows_use_jom=True" >> "$DEFAULT_PROFILE"
        fi

      shell: bash

    - run: conan remote remove "*"
      shell: bash

    - name: Create Conan hook to reduce conandata
      shell: bash
      run: |
        HOOK_DIR="$(conan config home)/extensions/hooks"
        HOOK_FILE="$HOOK_DIR/hook_reduce_conandata.py"

        mkdir -p "$HOOK_DIR"
        echo "from conan.tools.files import trim_conandata" > "$HOOK_FILE"
        echo "def post_export(conanfile):" >> "$HOOK_FILE"
        echo "  if conanfile.conan_data:" >> "$HOOK_FILE"
        echo "    trim_conandata(conanfile)" >> "$HOOK_FILE"
