/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculator_CONSTANTS_H
#define calculator_CONSTANTS_H

#include "calculator_types.h"



class calculatorConstants {
 public:
  calculatorConstants();

};

extern const calculatorConstants g_calculator_constants;



#endif
