find_package(googleapis CONFIG REQUIRED)
if (NOT ("${googleapis_RES_DIRS_RELEASE}" STREQUAL ""))
    set(EXTERNAL_GOOGLEAPIS_SOURCE "${googleapis_RES_DIRS_RELEASE}")
elseif (NOT ("${googleapis_RES_DIRS_RELWITHDEBINFO}" STREQUAL ""))
    set(EXTERNAL_GOOGLEAPIS_SOURCE "${googleapis_RES_DIRS_RELWITHDEBINFO}")
elseif (NOT ("${googleapis_RES_DIRS_MINSIZEREL}" STREQUAL ""))
    set(EXTERNAL_GOOGLEAPIS_SOURCE "${googleapis_RES_DIRS_MINSIZEREL}")
elseif (NOT ("${googleapis_RES_DIRS_DEBUG}" STREQUAL ""))
    set(EXTERNAL_GOOGLEAPIS_SOURCE "${googleapis_RES_DIRS_DEBUG}")
endif ()
