// THIS FILE IS AUTOGENERATED
#include "lngs-test.hpp"

// clang-format off
namespace lngs::test {
    namespace {
        const char resource[] = {
            "\x4c\x41\x4e\x47\x20\x68\x64\x72\x02\x00\x00\x00\x00\x01\x00\x00"
            "\x01\x00\x00\x00\x73\x74\x72\x73\x09\x00\x00\x00\x01\x00\x00\x00"
            "\x07\x00\x00\x00\xe9\x03\x00\x00\x00\x00\x00\x00\x0d\x00\x00\x00"
            "\x48\x65\x6c\x6c\x6f\x2c\x20\x77\x6f\x72\x6c\x64\x21\x00\x00\x00"
            "\x6c\x61\x73\x74\x00\x00\x00\x00"
        }; // resource
    } // namespace

    /*static*/ const char* Resource::data() { return resource; }
    /*static*/ std::size_t Resource::size() { return sizeof(resource); }
} // namespace lngs::test
// clang-format on
