#include <iostream>
#include <cstdio>
#include <FlexLexer.h>

extern "C"
{
    FILE * yyin = stdin;
    FILE * yyout = stdout;

    int yylex() { return 0; }
}

// generated by running: flex -+ --outfile test_package/basic_nr.cpp  test_package/basic_nr.l
#include "basic_nr.cpp"


