find_package(double-conversion REQUIRED CONFIG)
find_package(Eigen3 REQUIRED CONFIG)
find_package(EXPAT REQUIRED MODULE)
find_package(JPEG REQUIRED CONFIG)
find_package(OpenJPEG REQUIRED CONFIG)
find_package(PNG REQUIRED)
find_package(TIFF REQUIRED)
find_package(ZLIB REQUIRED)
