if(NOT TARGET Magnum::gl-info)
    if(CMAKE_CROSSCOMPILING)
        find_program(MAGNUM_GL_INFO_PROGRAM magnum-gl-info PATHS ENV PATH NO_DEFAULT_PATH)
    endif()
    if(NOT MAGNUM_GL_INFO_PROGRAM)
        set(MAGNUM_GL_INFO_PROGRAM "${CMAKE_CURRENT_LIST_DIR}/../../bin/magnum-gl-info")
    endif()
    get_filename_component(MAGNUM_GL_INFO_PROGRAM "${MAGNUM_GL_INFO_PROGRAM}" ABSOLUTE)
    add_executable(Magnum::gl-info IMPORTED)
    set_property(TARGET Magnum::gl-info PROPERTY IMPORTED_LOCATION ${MAGNUM_GL_INFO_PROGRAM})
endif()
