if(NOT TARGET Magnum::distancefieldconverter)
    if(CMAKE_CROSSCOMPILING)
        find_program(MAGNUM_DISTANCEFIELDCONVERTER_PROGRAM magnum-distancefieldconverter PATHS ENV PATH NO_DEFAULT_PATH)
    endif()
    if(NOT MAGNUM_DISTANCEFIELDCONVERTER_PROGRAM)
        set(MAGNUM_DISTANCEFIELDCONVERTER_PROGRAM "${CMAKE_CURRENT_LIST_DIR}/../../bin/magnum-distancefieldconverter")
    endif()
    get_filename_component(MAGNUM_DISTANCEFIELDCONVERTER_PROGRAM "${MAGNUM_DISTANCEFIELDCONVERTER_PROGRAM}" ABSOLUTE)
    add_executable(Magnum::distancefieldconverter IMPORTED)
    set_property(TARGET Magnum::distancefieldconverter PROPERTY IMPORTED_LOCATION ${MAGNUM_DISTANCEFIELDCONVERTER_PROGRAM})
endif()
