# Replacement for the fragile babysitting of optimization flags in
# https://github.com/openMVG/openMVG/blob/v2.0/src/cmakeFindModules/OptimizeForArchitecture.cmake

macro(OptimizeForArchitecture)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(x86)|(X86)|(i[0-9]86)|(amd64)|(AMD64)")
        if(MSVC)
            add_definitions("-D__SSE2__")
        endif()
        if(USE_AVX2)
            if(MSVC)
                add_compile_options("/arch:AVX2")
            else()
                add_compile_options("-mavx2")
            endif()
        elseif(USE_AVX)
            if(MSVC)
                add_compile_options("/arch:AVX")
            else()
                add_compile_options("-mavx")
            endif()
        endif()
    endif()
endmacro()
