find_package(minizip REQUIRED CONFIG)
link_libraries(minizip::minizip)

find_package(pugixml REQUIRED CONFIG)
link_libraries(pugixml::pugixml)

find_package(utf8cpp REQUIRED CONFIG)
link_libraries(utf8cpp::utf8cpp)

find_package(ZLIB REQUIRED CONFIG)
link_libraries(ZLIB::ZLIB)

if(WITH_CLIPPER)
    find_package(clipper REQUIRED CONFIG)
    link_libraries(clipper::clipper)
endif()
if(WITH_DRACO)
    find_package(draco REQUIRED CONFIG)
    link_libraries(draco::draco)
endif()
if(WITH_KUBAZIP)
    find_package(zip REQUIRED CONFIG)
    link_libraries(zip::zip)
endif()
if(WITH_OPENDDL)
    find_package(openddlparser REQUIRED CONFIG)
    link_libraries(openddlparser::openddlparser)
endif()
if(WITH_POLY2TRI)
    find_package(poly2tri REQUIRED CONFIG)
    link_libraries(poly2tri::poly2tri)
endif()
if(WITH_PUGIXML)
endif()
if(WITH_RAPIDJSON)
    find_package(RapidJSON REQUIRED CONFIG)
    link_libraries(rapidjson::rapidjson)
endif()
if(WITH_STB)
    find_package(stb REQUIRED CONFIG)
    link_libraries(stb::stb)
endif()
