set(CURSES_FOUND ON)
set(CURSES_INCLUDE_DIRS ${Curses_INCLUDE_DIRS})
set(CURSES_LIBRARIES ${Curses_LIBRARIES})
set(CURSES_CFLAGS ${Curses_DEFINITIONS} ${Curses_COMPILE_OPTIONS_C})
set(CURSES_HAVE_CURSES_H OFF)
set(CURSES_HAVE_NCURSES_H OFF)
if(CURSES_NEED_NCURSES)
    set(CURSES_HAVE_NCURSES_CURSES_H ON)
    set(CURSES_HAVE_NCURSES_NCURSES_H ON)
endif()

# For Conan v1 backward compatibility
string(TOUPPER "${CMAKE_BUILD_TYPE}" _CMAKE_BUILD_TYPE_UPPER)
set(CURSES_INCLUDE_DIRS ${CURSES_INCLUDE_DIRS} ${ncurses_INCLUDE_DIRS_${_CMAKE_BUILD_TYPE_UPPER}})
set(CURSES_LIBRARIES ${CURSES_LIBRARIES} ${ncurses_LIBRARIES_${_CMAKE_BUILD_TYPE_UPPER}})
set(CURSES_CFLAGS ${CURSES_CFLAGS} ${ncurses_DEFINITIONS_${_CMAKE_BUILD_TYPE_UPPER}} ${Curses_COMPILE_OPTIONS_C_${_CMAKE_BUILD_TYPE_UPPER}})

# Backward Compatibility
set(CURSES_INCLUDE_DIR ${CURSES_INCLUDE_DIRS})
set(CURSES_LIBRARY ${CURSES_LIBRARIES})

