name: Build single ref
run-name: Build ${{ inputs.package || 'zlib' }}/${{ inputs.version || '1.3.1' }}

on:
  push:
    paths-ignore:
      - 'recipes/**'
  pull_request:
    paths-ignore:
      - 'recipes/**'
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      version:
        type: string
        required: true
      upload:
        type: boolean
        required: false
        default: false
    secrets:
      ARTIFACTORY_USER:
        description: 'User to authenticate with Artifactory'
        required: true
      ARTIFACTORY_TOKEN:
        description: 'API Key to authenticate with Artifactory'
        required: true

  workflow_dispatch:
    inputs:
      package:
        type: string
        required: true
      version:
        type: string
        required: true
      upload:
        type: boolean
        required: false
        default: false

env:
  PACKAGE: ${{ inputs.package || 'zlib' }}
  VERSION: ${{ inputs.version || '1.3.1' }}
  REF: ${{ inputs.package || 'zlib' }}/${{ inputs.version || '1.3.1' }}

jobs:  
  prepare-matrix:
    runs-on: ubuntu-slim
    outputs:
      folder: ${{ steps.get_folder.outputs.result }}
      matrix: ${{ steps.search_shared_option.outputs.result }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            requirements.txt
            recipes/${{ env.PACKAGE }}

      - id: get_folder
        run: |
          folder=$(yq ".versions.\"${VERSION}\".folder" "recipes/${PACKAGE}/config.yml")
          echo "result=$folder"
          echo "result=$folder" >> "$GITHUB_OUTPUT"

      - uses: ./.github/actions/setup-conan

      - uses: ./.github/actions/setup-remote
        with:
          artifactory-user: ${{ secrets.ARTIFACTORY_USER }}
          artifactory-token: ${{ secrets.ARTIFACTORY_TOKEN }}
        if: ${{ github.ref == 'refs/heads/community_index' }}

      - uses: actions/github-script@v8
        id: search_shared_option
        with:
          script: |
            const {
              exitCode,
              stdout,
              stderr
            } = await exec.getExecOutput('conan', ['inspect', `recipes/${process.env.PACKAGE}/${{ steps.get_folder.outputs.result }}`, '--format=json']);
            if( exitCode != 0 ) {
              core.setFailed(`Could not parse recipe. error ${exitCode}: ${stderr}`);
              return
            }
            const info = JSON.parse(stdout)
            core.info(JSON.stringify(info))

            return {
              os: ['ubuntu-24.04', 'windows-2025', 'macos-14', 'ubuntu-24.04-arm', 'windows-11-arm'],
              shared: ( "shared" in info.options_definitions ) ? ['-o*/*:shared=False', '-o*/*:shared=True'] : (info.package_type == 'shared-library') ? ['-o*/*:shared=True'] : [''],
              build_type: ["Release"]
            };

      - if: github.ref == 'refs/heads/community_index'
        run: |
          conan export --version=$VERSION --no-remote recipes/$PACKAGE/${{ steps.get_folder.outputs.result }}
          conan upload -r community $REF --confirm --only-recipe
      - name: Collect logs
        if: failure()
        run: cat process.log || echo "No log file found"
        shell: bash
      - run: gh api rate_limit || echo "could not get gh rate limits"
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [prepare-matrix]
    env:
      FOLDER: recipes/${{ inputs.package || 'zlib' }}/${{ needs.prepare-matrix.outputs.folder }}
      SHARED: ${{ matrix.shared }}
      BUILD_TYPE: ${{ matrix.build_type }}
      CLI_ARGS: -sbuild_type=${{ matrix.build_type }} ${{ matrix.shared }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            requirements.txt
            ${{ env.FOLDER }}

      - uses: ./.github/actions/setup-conan
          
      - uses: ./.github/actions/setup-remote
        with:
          artifactory-user: ${{ secrets.ARTIFACTORY_USER }}
          artifactory-token: ${{ secrets.ARTIFACTORY_TOKEN }}

      - run: conan export --version=${{ env.VERSION }} --no-remote ${{ env.FOLDER }}

      - run: |
          CONAN_PATH=$(conan config home)
          PROFILE_PATH=$(conan profile path autodetected)
          COMPILER=$(awk -F "=" '/^compiler=/ {print $2}' $PROFILE_PATH)
          CPP_STDS=$(python3 -c "import yaml;import sys;print(*yaml.safe_load(sys.stdin)['compiler']['$COMPILER']['cppstd'])" < $CONAN_PATH/settings.yml)
          for cpp_std in $CPP_STDS; do
            if [ "$cpp_std" = "None" ]; then
              ARG=""
            else
              ARG="-s compiler.cppstd=$cpp_std"
            fi
            if ! conan profile show $ARG ${{ env.CLI_ARGS }}
            then
              continue
            fi
            conan graph info $ARG --require=${{ env.REF }} --build=missing --build=${{ env.REF }} ${{ env.CLI_ARGS }} --format=json > graph.json
            if jq -e 'any(.graph.nodes[]; .binary == "Invalid")' graph.json
            then
              continue
            else
              if [ "$cpp_std" != "None" ]
              then
                echo "compiler.cppstd=$cpp_std" >> $PROFILE_PATH
              fi
              echo "CODE=0" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          done
          echo "CODE=6" >> "$GITHUB_OUTPUT"
        id: conan_install
        name: Conan Graph
        shell: bash

      - if: ${{ steps.conan_install.outputs.CODE != 6 }}
        name: Remove system OpenSSL directory
        shell: bash
        run: |
          paths=(
            "/c/Program Files/OpenSSL"
            "/c/Program Files/OpenSSL-Win64"
            "/c/Program Files (x86)/OpenSSL"
            "/c/Strawberry"
            "/c/Program Files/MySQL"
            "/c/Program Files/Amazon"
            "/c/tools/php"
            "/c/mingw64"
          )
          rm -f /c/Windows/System32/libssl-*.dll
          rm -f /c/Windows/System32/libcrypto-*.dll
          
          for path in "${paths[@]}"; do
            rm -rf "$path" &
          done
          wait

      - run: conan install --require=${{ env.REF }} --build=missing --build=${{ env.REF }} ${{ env.CLI_ARGS }}
        name: Conan Install
        if: ${{ steps.conan_install.outputs.CODE != 6 }}

      - run: conan test ${{ env.FOLDER }}/test_package/conanfile.py ${{ env.REF }} --build=missing ${{ env.CLI_ARGS }}
        if: ${{ steps.conan_install.outputs.CODE != 6 }}
      - run: conan upload -r community ${{ env.REF }} --confirm
        if: ${{ steps.conan_install.outputs.CODE != 6 && inputs.upload }}
      - name: Collect logs
        if: failure()
        run: cat process.log || echo "No log file found"
        shell: bash
      - run: gh api rate_limit || echo "could not get gh rate limits"
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
